### ISSUE TITLE
One ui 6 says "all notifications from this app are blocked"

### ISSUE THREAD

**Issue by silvaf6** [anandnet/Harmony-Music#114]
**Describe the bug**
It shows the player. Im not sure if something is related to require to "keep the app open" and unrestricted access" to download over 100 songs over night. Like 10 minutes per song (im a new user). 
Installed the arm8 version

Since I've installed it on one Ui 6 i see it shows up as "all notifications from this app are blocked"

**To Reproduce**
Check permissions and notifications

**Screenshots**
![Screenshot_20231227_100927_Settings](https://github.com/anandnet/Harmony-Music/assets/38669846/1a4f4ab7-5e55-4faf-817c-692a89c733fc)

**Smartphone (please complete the following information):**
 - Device: Samsung fold 4
 - OS: One Ui 6, android 14

Since I'm new and trying to find an offline music streaming alternative without wierd algorithms and trackings, dont know if that is normal. I did factory reset because other apps are still not getting notifications.  I regret upgrading to one ui 6. Next time ill wait a few months.
Is it by defalt to take hours to download an album for offline play?

Thanks and good job, i appreciate it

Btw, it is winter, im doing nothing on my phone besides writing this, but keeping the task open to download my music is heating up and draining alot of battery

**Comment by anandnet** [comment]
i don't know why it is taking 10min to download one song (seems due to slow connection), for me if feels slower when i use mobile data but in wifi it is not more than 10sec.
This app doesn't provide any additional notification other than Player controller notification. if it blocking Player controller notification/Music service notification, please let me know i'll look into that.

For you device safety please avoid continuous dowloading unless you want to use your phone as a heater/warmer in this winter 😄.  you can tap on dowloading status icon it will pause the downloading next time when you click downloading icon it will resume from there.

to keep this open in background you can enable "Ignore battery optimization" from settings.

**Comment by silvaf6** [comment]
Im with a wifi 5g connection of about 250mb, so i dunno. Ive trying a similar app and it is the same thing. Portuguese servers might be slower. Anyways, im on holidays and ive got the time 😂 but a download progress bar norification would come in handy. Thanks!
