### ISSUE TITLE
Improve load times of songs and Homepage

### ISSUE THREAD

**Issue by anxiouslelimo** [anandnet/Harmony-Music#133]
**Is your feature request related to a problem or new idea? Please describe.**
I have seen in other apps like Innertune and Rimusic (fork of Vmusic) the load times of songs and homepage are much faster than in Harmony Music

**Describe the solution you'd like**
Faster Load times for songs and homepage

**Comment by anandnet** [comment]
I can understand your concern, Harmony Music is built on Flutter which uses Dart language, Dart is single threaded language so, we can't except multithreaded behaviour and it is very difficult to produce multithreaded behaviour, However we can use Isolate but each Isolate's memory is completely isolated.
In addition to that Flutter/Flutter Plugin uses Platform channel to interact with native platform/native plugin which can cause minor delay.

- To reduce delay in Homepage loading i have added a option to set no of contents in settings, but still minimum two api requests is getting called each time.  

Currently i'm experimenting for this enhancement, Lets hope for the good :)

**Comment by anandnet** [comment]
For Home screen loading issue i've added feature to cached home screen conntent data. which loads home screen almost instant.
For Song loading i have tried multiple scenarios but all are taking almost same time so, i don't think so, it is possible due to single threaded behaviour. for now i'm closing this however i will keep looking new ways for improving this.
