### ISSUE TITLE
Export downloaded songs to mp3 files

### ISSUE THREAD

**Issue by NguyenTrongThinh** [anandnet/Harmony-Music#157]
**Is your feature request related to a problem or new idea? Please describe.**
I have an DAC converter that plugs to USB C port. The manufacturer give a music player application that can stream music file as bit perfect and the DAC is responsible for decode the music. This solution can by pass the system decode which is lower quality in comparison to the USB DAC. So is it possible to share the download songs with other music player application. Can be shared by exporting downloaded songs to mp3 files?

**Describe the solution you'd like**
An option to export downloaded songs to mp3 files.

**Describe alternatives you've considered**
Support USB DAC bit streaming or DLNA receiver if cannot export downloaded song to mp3 files.

**Comment by anandnet** [comment]
Hello @NguyenTrongThinh, i will add an option to export downloaded song file from app dir to external dir. for now, please give a long press on "Streaming quality" section you will see hidden oprion to change download dir. you can choose external dir where file will be accessible to you.

- please do not move the download file from initial downloaded location, otherwise song will not be playable offline due to file location mismach in harmony music

- mp3 format is not available. available formats: opus/ogg  and m4a

**Comment by anandnet** [comment]
added, check v1.9.0.
