### ISSUE TITLE
Dev?

### ISSUE THREAD

**Issue by DeadSecTr** [anandnet/Harmony-Music#227]
There are so many bugs,why is dev not reacting on these?

**Comment by encryptionstudio** [comment]
Probably because it's a hobby project? If you want these bugs to be fixed just learn programming with dart/flutter and do it yourself or wait for the dev(s) 🤷‍♂️
I think I'll do some bug hunting soon, when I have free time

**Comment by encryptionstudio** [comment]
Sorry I didn't wanted to sound offensive or so, my fault

**Comment by aidzmtsk** [comment]
> There are so many bugs,why is dev not reacting on these? 

Most bugs aren't actionable by themselves and need to be triaged so that they can be actionable. Bug triaging requires a lot of time which I can understand the developer struggles to find, especially while maintaining this project.

You can help with the process though by going through issues and making sure they can be actionable (They may be missing details here and there. The root problem can be determined with more details.)

[There's a really good article regarding this exact problem/solution by the KDE project, which maintains many important/popular projects like Plasma Desktop, Krita, Kdenlive, etc.](https://pointieststick.com/2024/03/09/how-you-help-with-quality/)

I am a new user and right now it's finals season so it's difficult for me to help. I hope this gives you more of an idea of how Open Source projects work :)
