### ISSUE TITLE
There must be 2 different audio files for video and audio

### ISSUE THREAD

**Issue by techy2245** [anandnet/Harmony-Music#266]
There must be 2 different audio files for video and audio as even the audio has the audio of the scenes from the original video which is kinda annoying

**Comment by anandnet** [comment]
could you please provide any example ?

**Comment by techy2245** [comment]
if im playing song called somebody by the chainsmokers from yt the yt audio and the audio of the scenes happening in the video will be heard and this is existing when i play the song from album option even though it is in audio way.....please fix this asap

**Comment by anandnet** [comment]
If you listen music video, the scenes audio will obviously appear, search this song in this app and go to songs sections find this rather than videos

 or

 you can listen this songs from original album which is appearing in search. Songs section contains original audio.

Hope this would be helpful.

**Comment by techy2245** [comment]
i always use the original album to listen to songs but it too has the same issue

**Comment by anandnet** [comment]
Unfortunately 😔 i can't do much on content part, this app plays exactly same content as yt or ytm. If you find any thing diff i will try to fix it🙂.
