### ISSUE TITLE
Showing full song name and showing album cover art for the song instead of image from the song video

### ISSUE THREAD

**Issue by dainvincible1** [anandnet/Harmony-Music#32]
It would be better if the app shows full song name. In the image below the name of the song is "summertime sadness" but it only shows "summertime"
![image](https://github.com/anandnet/Harmony-Music/assets/127825700/0a130237-2796-4383-94b1-e98fda595c2b)

It would look better if there is album cover art for songs and not the image from the song video.
![image](https://github.com/anandnet/Harmony-Music/assets/127825700/9678deb7-042f-443d-b973-aee56b92ff6b)
![image](https://github.com/anandnet/Harmony-Music/assets/127825700/1c335a77-2b8a-4834-8439-67fc3785f2ef)

**Comment by anandnet** [comment]
@dainvincible1 i can't do much in video album-art part because the thumnail shown here is return from ytmusic api.
if i consider replacing video thumb with album-art manually, there are so many unnecessary cases comes into picture so i'm ignoring this for now.

and full name issue i have fixed in v1.4.0
