### ISSUE TITLE
Harmony Music not working on linux

### ISSUE THREAD

**Issue by Desperatioo** [anandnet/Harmony-Music#378]
**Describe the bug**
The player doesn't work, it's always stuck at 0:00, most of the music players worked on my Laptop so i'm guessing the problem here is the app

**To Reproduce**
1. Go to Harmony Music
2. Click on any song
3. Song don't play and there's no error

**Expected behavior**
The song plays

**Screenshots**
![Screenshot from 2024-12-07 14-39-50](https://github.com/user-attachments/assets/bd1a9c89-f503-4907-8fda-d7af365a3ead)

**Smartphone (please complete the following information):**
 - Device: Lenovo Ideapad 320
 - OS: Linux(specifically ZorinOs)

**Additional context**

**Comment by trunars** [comment]
Install MPV package in linux if any of binaries is not working

For Debian:
sudo apt install mpv

**Comment by blacklizzt** [comment]
why your playback looks so different to mine? mine looks very similar to the Android version

**Comment by Desperatioo** [comment]
> Install MPV package in linux if any of binaries is not working
> 
> For Debian: sudo apt install mpv

I tried it but i dont think it works, whether im doing it wrong or its because of the file i used to import my files in harmony music

**Comment by Desperatioo** [comment]
> why your playback looks so different to mine? mine looks very similar to the Android version
> 
> ![image](https://private-user-images.githubusercontent.com/89076095/393762852-b300e827-0951-4758-bde0-da1c1e1591e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDQ0MjEsIm5iZiI6MTczMzc0NDEyMSwicGF0aCI6Ii84OTA3NjA5NS8zOTM3NjI4NTItYjMwMGU4MjctMDk1MS00NzU4LWJkZTAtZGExYzFlMTU5MWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDExMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0Y2M5Y2Y1M2ZkZGM5OGIwYjIyYmFjODcyZmQwNTgzMTg4MDFmNWU2N2JjMjBjODc3MDZkNmY0Yzk0MDdjYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SjVqluQHQsfC7FPEHysDCgNZlelYOsJDRuzLnq1lhec)

Thats pretty sick!
Mind if you send your backup files for these to check if my backup files are the problem? 
Or is there a way to reset all my data?

**Comment by blacklizzt** [comment]
what version did you download? mine is .deb since i am using debian

**Comment by Desperatioo** [comment]
> what version did you download? mine is .deb since i am using debian

I used .deb as well

**Comment by anandnet** [comment]
@Desperatioo this is happening because probably you are using your phone Appdata backup file into your pc.(it was meant to use in same device by design).

As a work around,
1. In your phone you can fall back to player ui mode to standard and make sure bottom navigation bar is disabled, then create a backup file and use this file to restore into your pc.

Or

try `rm -r ~/.local/share/harmonymusic/db`

it will delete all the databases and reset the app. (all the bookmarked/offline playlists and albums will be removed).

________________________________
For long term fix i will add an option restore to default settings. and feature to export playlist so that playlist can be imported/exported across all available Hm clients.

**Comment by anandnet** [comment]
Now backup file can be used across all Hm clients.
