### ISSUE TITLE
I dont know if its a bug or a feature but if after importing playlist to harmony music, i make the playlist private in youtube music the playlist doesnt open

### ISSUE THREAD

**Issue by dainvincible1** [anandnet/Harmony-Music#39]

**Comment by anandnet** [comment]
Of course playlist won't open, if you make playlist private in yt music. because "bookmarked playlists" songs list doesn't get stored locally, every time it calls api for songs list.

if you are concerned about playlist privacy please choose "Unlisted" option instead of "Private". it will allow accessing that playlist through sharable link. no one can see your playlist publically untill you share this playlist link.
Using this option you will also able to import/access in that playlist in Harmony Music.

Closing...
